In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("marketing_AB 2.csv")

In [ ]:
df.shape

(588101, 7)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 588101 entries, 0 to 588100
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Unnamed: 0     588101 non-null  int64
 1   user id        588101 non-null  int64
 2   test group     588101 non-null  object
 3   converted      588101 non-null  bool
 4   total ads      588101 non-null  int64
 5   most ads day   588101 non-null  object
 6   most ads hour  588101 non-null  int64
dtypes: bool(1), int64(4), object(2)
memory usage: 27.5+ MB

In [ ]:
df.head()

,Unnamed: 0,user id,test group,converted,total ads,most ads day,most ads hour
0,0,1069124,ad,False,130,Monday,20
1,1,1119715,ad,False,93,Tuesday,22
2,2,1144181,ad,False,21,Tuesday,18
3,3,1435133,ad,False,355,Tuesday,10
4,4,1015700,ad,False,276,Friday,14

In [ ]:
df.drop("Unnamed: 0", axis=1, inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 588101 entries, 0 to 588100
Data columns (total 6 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   user id        588101 non-null  int64
 1   test group     588101 non-null  object
 2   converted      588101 non-null  bool
 3   total ads      588101 non-null  int64
 4   most ads day   588101 non-null  object
 5   most ads hour  588101 non-null  int64
dtypes: bool(1), int64(3), object(2)
memory usage: 23.0+ MB

In [ ]:
df.head()

   user id test group  converted  total ads most ads day  most ads hour
0  1069124         ad      False        130       Monday             20
1  1119715         ad      False         93      Tuesday             22
2  1144181         ad      False         21      Tuesday             18
3  1435133         ad      False        355      Tuesday             10
4  1015700         ad      False        276       Friday             14

In [ ]:
df.isnull().sum()

user id          0
test group       0
converted        0
total ads        0
most ads day     0
most ads hour    0
dtype: int64

In [ ]:
(df.isnull().sum()/len(df))*100

user id          0.0
test group       0.0
converted        0.0
total ads        0.0
most ads day     0.0
most ads hour    0.0
dtype: float64

In [ ]:
df['most ads day'].fillna('Unknown', inplace=True)

/tmp/ipykernel_881/1231528668.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['most ads day'].fillna('Unknown', inplace=True)

In [ ]:
df['test group'].fillna('Unknown', inplace=True)

/tmp/ipykernel_881/593672019.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['test group'].fillna('Unknown', inplace=True)

In [ ]:
df.isnull().sum()

user id          0
test group       0
converted        0
total ads        0
most ads day     0
most ads hour    0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 588101 entries, 0 to 588100
Data columns (total 6 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   user id        588101 non-null  int64
 1   test group     588101 non-null  object
 2   converted      588101 non-null  bool
 3   total ads      588101 non-null  int64
 4   most ads day   588101 non-null  object
 5   most ads hour  588101 non-null  int64
dtypes: bool(1), int64(3), object(2)
memory usage: 23.0+ MB

In [ ]:
print(df['test group'].unique())

['ad' 'psa']

In [ ]:
print(df['most ads day'].unique())

['Monday' 'Tuesday' 'Friday' 'Saturday' 'Wednesday' 'Sunday' 'Thursday']

In [ ]:
print(df['converted'].unique())

[False  True]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 588101 entries, 0 to 588100
Data columns (total 6 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   user id        588101 non-null  int64
 1   test group     588101 non-null  object
 2   converted      588101 non-null  bool
 3   total ads      588101 non-null  int64
 4   most ads day   588101 non-null  object
 5   most ads hour  588101 non-null  int64
dtypes: bool(1), int64(3), object(2)
memory usage: 23.0+ MB

In [ ]:
df.duplicated().sum()
df['most ads hour'].min(), df['most ads hour'].max()
df['total ads'].describe()

count    588101.000000
mean         24.820876
std          43.715181
min           1.000000
25%           4.000000
50%          13.000000
75%          27.000000
max        2065.000000
Name: total ads, dtype: float64

In [ ]:
df.to_csv('marketing_AB_cleaned.csv', index=False)

In [ ]:
from google.colab import files

files.download('marketing_AB_cleaned.csv')